### ISSUE TITLE
The HTML <center> tag doesn't appear in red/pink like another tag?

### ISSUE THREAD

**Issue by Lusiiky** [fabiospampinato/vscode-monokai-night#10]
Hello,

I noticed that the `<center>` tag doesn't appear in red/pink like any tag in HTML.
![image](https://user-images.githubusercontent.com/29005043/136024946-96bc9a74-d42d-4737-84c6-6d97e659c0d3.png)
Is it normal?

Thank you,
Lupsoris

**Comment by fabiospampinato** [comment]
Does that look differently with other themes? If so can you post the code and the name of the theme?

**Comment by ImSeaWorld** [comment]
The `center` tag is not supported in HTML5. While the browser knows the difference and will still center the text, the syntax highlighter you're using is HTML5.

Hopefully this answers the question

**Comment by fabiospampinato** [comment]
Fixed by @SmitAkbari26 in #14
