### ISSUE TITLE
Saturated buttons

### ISSUE THREAD

**Issue by arunopal** [fabiospampinato/vscode-monokai-night#12]
Seriously, gray buttons? Looks as if the buttons are unavailable. Please add the characteristic blue accent colours to the buttons.
![monokainight-issuecreation](https://user-images.githubusercontent.com/92020881/186068109-e17df38b-20ba-4593-bf23-061528ba14ee.png)

**Comment by fabiospampinato** [comment]
It looks like this got addressed by your own PR.
